name: Go

on:
  schedule:
    # run every Sunday
    - cron: '0 13 * * 0'
  push:
    branches:
      - main
      - release-0.1x
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        image:
          - mongo:4.2
          - mongo:4.4
          - mongo:5.0
          - percona/percona-server-mongodb:4.2
          - percona/percona-server-mongodb:4.4
          - percona/percona-server-mongodb:5.0

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ${{ github.workspace }}/go.mod

      - name: Run tests with code coverage
        run: |
          TEST_MONGODB_IMAGE=${{ matrix.image }} make test-cluster
          sleep 10
          make test-cover
          make test-cluster-clean

      - name: Upload coverage results
        uses: codecov/codecov-action@v3
        with:
          file: cover.out
          flags: agent
          env_vars: GO_VERSION,TEST_MONGODB_IMAGE
          fail_ci_if_error: false
