name: Go

on:
  schedule:
    # run every Sunday
    - cron: '0 13 * * 0'
  push:
    branches:
      - main
      - release-0.1x
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        image:
          - mongo:4.4
          - mongo:5.0
          - mongo:6.0
          - mongo:7.0
          - mongo:8.0
          - mongo:latest
          - percona/percona-server-mongodb:4.4
          - percona/percona-server-mongodb:5.0
          - percona/percona-server-mongodb:6.0
          - percona/percona-server-mongodb:7.0
          - percona/percona-server-mongodb:latest

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ github.workspace }}/go.mod

      - name: Test
        run: |
          TEST_MONGODB_IMAGE=${{ matrix.image }} make test-cluster
          sleep 10
          make test-race
          make test-cluster-clean

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          echo "--- Environment variables ---"
          env | sort
          echo "--- GO Environment ---"
          go env | sort
          echo "--- Git status ---"
          git status
          echo "--- Docker logs ---"
          docker compose logs
          echo "--- Docker ps ---"
          docker compose ps -a
