name: Go

on:
  schedule:
    # run every Sunday
    - cron: "0 13 * * 0"
  push:
    branches:
      - master
      - exporter_v2
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
        matrix:
            image:
                - "mongo:3.6"
                - "mongo:4.0"
                - "mongo:4.2"
                - "percona/percona-server-mongodb:3.6"
                - "percona/percona-server-mongodb:4.0"
                - "percona/percona-server-mongodb:4.2"
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Initialize dependencies and linters
      run: |
        make init

    - name: Test
      run: |
        TEST_MONGODB_IMAGE=${{ matrix.image }} make test-cluster
        make test
        make test-cluster-clean

    - name: Run checks/linters
      run: |
        # use GITHUB_TOKEN because only it has access to GitHub Checks API
        bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number | env REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-check
        bin/golangci-lint run -c=.golangci.yml --out-format=line-number | env REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }} bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-review

    - name: Diff
      run: |
        make format
        git diff --exit-code
